/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Fixed: TypeScript strict import, Lip Sync Logic & Console Warnings
*/

import * as THREE from 'three'
import React, { useEffect, useMemo, useRef, useState } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import type { GLTF } from 'three-stdlib'
import { useA2FStream } from './useA2FStream'
import { useChatStore } from '../store/useChatStore'
import { Lipsync } from 'wawa-lipsync'
interface FacialExpressionValues {
  [key: string]: number | undefined
}

const facialExpressions: { [key: string]: FacialExpressionValues } = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.17,
    noseSneerRight: 0.14,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78,
    browInnerUp: 0.45,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.35,
    mouthFunnel: 0.35,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.57,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39,
    eyeLookUpRight: 0.4,
    eyeLookInLeft: 0.96,
    eyeLookInRight: 0.96,
    jawOpen: 0.96,
    mouthDimpleLeft: 0.96,
    mouthDimpleRight: 0.96,
    mouthStretchLeft: 0.27,
    mouthStretchRight: 0.28,
    mouthSmileLeft: 0.55,
    mouthSmileRight: 0.38,
    tongueOut: 0.96,
  },
}

type GLTFResult = GLTF & {
  nodes: {
    Wolf3D_Hair: THREE.SkinnedMesh
    Wolf3D_Outfit_Top: THREE.SkinnedMesh
    Wolf3D_Outfit_Bottom: THREE.SkinnedMesh
    Wolf3D_Outfit_Footwear: THREE.SkinnedMesh
    Wolf3D_Body: THREE.SkinnedMesh
    EyeLeft: THREE.SkinnedMesh
    EyeRight: THREE.SkinnedMesh
    Wolf3D_Head: THREE.SkinnedMesh
    Wolf3D_Teeth: THREE.SkinnedMesh
    Hips: THREE.Bone
  }
  materials: {
    Wolf3D_Hair: THREE.MeshStandardMaterial
    Wolf3D_Outfit_Top: THREE.MeshStandardMaterial
    Wolf3D_Outfit_Bottom: THREE.MeshStandardMaterial
    Wolf3D_Outfit_Footwear: THREE.MeshStandardMaterial
    Wolf3D_Body: THREE.MeshStandardMaterial
    Wolf3D_Eye: THREE.MeshStandardMaterial
    Wolf3D_Skin: THREE.MeshStandardMaterial
    Wolf3D_Teeth: THREE.MeshStandardMaterial
  }
  animations: any[]
}

type ZivaProps = {
  audioUrl?: string | null;
  expression?: string; // New prop
  expressionTrigger?: number; // Trigger to re-apply expressions
  animation?: string;  // New prop
  animationTrigger?: number; // Trigger to replay animations
} & React.JSX.IntrinsicElements['group']

export function ZivaA2F({ audioUrl, expression, expressionTrigger, animation, animationTrigger, ...props }: ZivaProps) {
  const LERP_SPEED = 0.25
  const SPEAKING_MOUTH_EXPRESSION_ATTENUATION = 0.25

  const group = useRef<THREE.Group>(null)
  const { scene } = useGLTF('/models/Ziva.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult

  // 2. Animation Logic (With Warning Fixes)
  const { animations: clips } = useGLTF('/models/Animations.glb')

  useMemo(() => {
    if (clips) {
      clips.forEach((clip) => {
        if (clip.tracks) {
          // Filter out tracks that cause "No target node found" warnings
          clip.tracks = clip.tracks.filter((track) => {
            const trackName = track.name.toLowerCase();
            return !trackName.includes('end') &&
              !trackName.includes('nub') &&
              !trackName.includes('armature');
          });

          // Rename mixamo bones to match Ready Player Me skeleton
          clip.tracks.forEach((track) => {
            track.name = track.name.replace('mixamorig', '')
          })
        }
      })
    }
  }, [clips])

  const { actions, names } = useAnimations(clips || [], group)
  const [currentAnimation, setCurrentAnimation] = useState(() => names[0] || 'Idle')
  const [currentExpression, setCurrentExpression] = useState('default')
  const animationTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const expressionTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const wasAudioPlayingRef = useRef(false)
  const preAudioAnimationRef = useRef<string | null>(null)
  const currentAnimationRef = useRef(currentAnimation)
  const desiredAnimationRef = useRef<string>('Idle')

  // Handle expression changes with auto-reset to default after 2 seconds
  useEffect(() => {
    if (expression && expression !== 'default') {
      setCurrentExpression(expression)

      // Clear any existing timeout
      if (expressionTimeoutRef.current) {
        clearTimeout(expressionTimeoutRef.current)
      }

      // Reset to default after 2 seconds
      expressionTimeoutRef.current = setTimeout(() => {
        setCurrentExpression('default')
      }, 2000)
    } else if (expression === 'default') {
      setCurrentExpression('default')
    }

    return () => {
      if (expressionTimeoutRef.current) {
        clearTimeout(expressionTimeoutRef.current)
      }
    }
  }, [expression, expressionTrigger])

  useEffect(() => {
    // If parent provides an animation, use it. Otherwise, default/idle.
    if (animation && names.includes(animation)) {
      setCurrentAnimation(animation)

      // Clear any existing timeout
      if (animationTimeoutRef.current) {
        clearTimeout(animationTimeoutRef.current)
      }

      // Set timeout to return to Idle after 30 seconds (unless already Idle)
      if (animation !== 'Idle') {
        animationTimeoutRef.current = setTimeout(() => {
          setCurrentAnimation('Idle')
        }, 10000)
      }
    }

    return () => {
      if (animationTimeoutRef.current) {
        clearTimeout(animationTimeoutRef.current)
      }
    }
  }, [animation, names, animationTrigger]) // Added animationTrigger to dependencies

  useEffect(() => {
    currentAnimationRef.current = currentAnimation
  }, [currentAnimation])

  useEffect(() => {
    desiredAnimationRef.current = (animation && names.includes(animation)) ? animation : 'Idle'
  }, [animation, names])

  useEffect(() => {
    if (!currentAnimation || !actions[currentAnimation]) return

    const action = actions[currentAnimation]
    action
      .reset()
      .fadeIn(0.5)
      .play()

    // Listen for animation completion and return to Idle
    // (This handles animations that complete before 30s timeout)
    const onFinished = () => {
      if (currentAnimation !== 'Idle') {
        setCurrentAnimation('Idle')
      }
    }

    // Set loop mode - Idle and Talking should loop, others play once
    if (currentAnimation === 'Idle' || currentAnimation === 'Talking') {
      action.setLoop(THREE.LoopRepeat, Infinity)
    } else {
      action.setLoop(THREE.LoopOnce, 1)
      action.clampWhenFinished = true
      // @ts-ignore - mixer property exists at runtime
      const mixer = action.getMixer()
      mixer?.addEventListener('finished', onFinished)
    }

    return () => {
      action?.fadeOut(0.5)
      // @ts-ignore
      const mixer = action?.getMixer()
      mixer?.removeEventListener('finished', onFinished)
    }
  }, [currentAnimation, actions])

  // 3. Audio & A2F Setup
  const audioRef = useRef<HTMLAudioElement | null>(null)
  const autoplayRetryArmedRef = useRef(false)
  const a2fFrames = useChatStore(state => state.a2fFrames)

  // Fallback lipsync for when A2F is offline
  const lipsyncRef = useRef<Lipsync | null>(null)

  // Initialize Lipsync once to prevent AudioContext limits (max 6 in Chrome)
  useEffect(() => {
    lipsyncRef.current = new Lipsync()

    const unlockAudioContext = () => {
      const ac = (lipsyncRef.current as any)?.audioContext;
      if (ac && ac.state === 'suspended') {
        ac.resume().catch(() => { });
      }
    };

    window.addEventListener('pointerdown', unlockAudioContext);
    window.addEventListener('keydown', unlockAudioContext);

    return () => {
      window.removeEventListener('pointerdown', unlockAudioContext);
      window.removeEventListener('keydown', unlockAudioContext);
      try {
        (lipsyncRef.current as any)?.audioContext?.close()
      } catch (e) { }
    }
  }, [])

  // Use our new A2F stream hook
  const { updateBlendshapes } = useA2FStream(
    audioRef,
    a2fFrames,
    nodes.Wolf3D_Head,
    nodes.Wolf3D_Teeth
  )

  useEffect(() => {
    if (!audioUrl) {
      if (audioRef.current) {
        audioRef.current.pause()
        audioRef.current.removeAttribute('src')
        audioRef.current.load()
        audioRef.current = null
      }
      return
    }

    // Create a NEW Audio element
    const audio = new Audio()
    audio.crossOrigin = 'anonymous'
    audio.loop = false
    audio.src = audioUrl
    audioRef.current = audio

    // Only connect wawa-lipsync if we have NO A2F frames
    if (lipsyncRef.current && (!a2fFrames || a2fFrames.length === 0)) {
      lipsyncRef.current.connectAudio(audio)
    }

    // Drive Talking animation while audio is playing.
    const onPlay = () => {
      wasAudioPlayingRef.current = true
      if (actions['Talking']) {
        if (currentAnimationRef.current !== 'Talking') {
          preAudioAnimationRef.current = currentAnimationRef.current
        }
        setCurrentAnimation('Talking')
      }
    }

    const onStop = () => {
      if (!wasAudioPlayingRef.current) return
      wasAudioPlayingRef.current = false

      const desired = desiredAnimationRef.current
      if (desired !== 'Talking') {
        setCurrentAnimation(desired)
      } else if (preAudioAnimationRef.current && preAudioAnimationRef.current !== 'Talking') {
        setCurrentAnimation(preAudioAnimationRef.current)
      } else {
        setCurrentAnimation('Idle')
      }
      preAudioAnimationRef.current = null
    }

    audio.addEventListener('play', onPlay)
    audio.addEventListener('ended', onStop)
    audio.addEventListener('pause', onStop)

    const tryPlay = async () => {
      try {
        await audio.play()
      } catch (e) {
        if (!autoplayRetryArmedRef.current) {
          autoplayRetryArmedRef.current = true
          const retryOnce = () => {
            window.removeEventListener('pointerdown', retryOnce)
            autoplayRetryArmedRef.current = false
            void tryPlay()
          }
          window.addEventListener('pointerdown', retryOnce, { once: true })
        }
        console.warn('Audio autoplay blocked; will retry on user gesture.', e)
      }
    }

    const handleCanPlay = () => {
      void tryPlay()
    }

    audio.addEventListener('canplay', handleCanPlay, { once: true })
    audio.load()

    return () => {
      audio.removeEventListener('canplay', handleCanPlay)
      audio.removeEventListener('play', onPlay)
      audio.removeEventListener('ended', onStop)
      audio.removeEventListener('pause', onStop)
    }
  }, [audioUrl, actions])

  // 4. Blinking
  const [blink, setBlink] = useState(false)
  useEffect(() => {
    let blinkTimeout: ReturnType<typeof setTimeout>
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true)
        setTimeout(() => {
          setBlink(false)
          nextBlink()
        }, 200)
      }, THREE.MathUtils.randInt(1000, 5000))
    }
    nextBlink()
    return () => clearTimeout(blinkTimeout)
  }, [])

  // Calculate the actual expression to use: currentExpression > Default
  const activeExpression = currentExpression || 'default'

  // 6. Frame Loop
  useFrame(() => {
    const head = nodes.Wolf3D_Head
    const teeth = nodes.Wolf3D_Teeth

    if (!head) return

    // A. Analyze Audio (Fallback to wawa-lipsync if no A2F frames)
    const isAudioPlaying = audioRef.current && !audioRef.current.paused && !audioRef.current.ended

    let fallbackViseme: string | null = null;

    if (isAudioPlaying) {
      if (a2fFrames && a2fFrames.length > 0) {
        // High-Fidelity NVIDIA Audio2Face
        updateBlendshapes()
      } else if (lipsyncRef.current) {
        // Client-side heuristic fallback
        lipsyncRef.current.processAudio()
        fallbackViseme = lipsyncRef.current.viseme
      }
    }

    // C. Expressions
    // Apply expressions even while speaking so the tone shows on the face.
    // Visemes will still drive mouth shapes; we attenuate mouth/jaw expression a bit while speaking.
    const expressionValues = (facialExpressions[activeExpression] || {})

    // D. Morph Targets
    Object.keys(head.morphTargetDictionary || {}).forEach((key) => {
      const targetIndex = head.morphTargetDictionary![key]
      const teethIndex = teeth.morphTargetDictionary![key]

      let targetValue = 0

      // Base Expression
      if (expressionValues[key] !== undefined) {
        const raw = expressionValues[key]!
        const shouldAttenuateForSpeech = isAudioPlaying && (
          key.startsWith('mouth') ||
          key.startsWith('jaw') ||
          key.startsWith('tongue')
        )
        targetValue = shouldAttenuateForSpeech ? (raw * SPEAKING_MOUTH_EXPRESSION_ATTENUATION) : raw
      }

      // Blinking
      if (key === 'eyeBlinkLeft' || key === 'eyeBlinkRight') {
        targetValue = blink ? 1 : 0
      }

      // If A2F is active, it handles lip sync. We only lerp our own custom expressions here.
      if (isAudioPlaying && a2fFrames && a2fFrames.length > 0) {
        if (key.startsWith('jaw') || key.startsWith('mouth') || key.startsWith('cheek') || key.startsWith('viseme_')) {
          return; // Skip overwriting what A2F just did in updateBlendshapes()
        }
      }

      // Fallback Lipsync Logic
      if (isAudioPlaying && (!a2fFrames || a2fFrames.length === 0)) {
        if (key.startsWith('viseme_') && key === fallbackViseme) {
          targetValue = 1.0 // VISEME_INTENSITY
        }
      }

      const lerpSpeed = (isAudioPlaying && (!a2fFrames || a2fFrames.length === 0) && key.startsWith('viseme_'))
        ? 0.5 // VISEME_LERP_SPEED
        : LERP_SPEED

      // Apply with lerp
      head.morphTargetInfluences![targetIndex] = THREE.MathUtils.lerp(
        head.morphTargetInfluences![targetIndex],
        targetValue,
        lerpSpeed
      )

      if (teethIndex !== undefined) {
        teeth.morphTargetInfluences![teethIndex] = THREE.MathUtils.lerp(
          teeth.morphTargetInfluences![teethIndex],
          targetValue,
          lerpSpeed
        )
      }
    })
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
      <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
      <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
    </group>
  )
}

useGLTF.preload('/models/Ziva.glb')
useGLTF.preload('/models/Animations.glb')